FROM microsoft/aspnetcore-build:2.0.2-stretch
WORKDIR /app

COPY Com.Danliris.Service.Spinning.WebApi/*.csproj .
RUN dotnet restore

COPY Com.Danliris.Service.Spinning.WebApi/. .
RUN dotnet publish --output /out/ --configuration Release